---
- name: Install docker and docker-compose
  hosts: server
  become: yes
  tasks:
    - name: Update yum repo and cache
      yum: update_cache=yes

    - name: Install docker
      yum:
        name: docker
        state: present

    - name: start docker
      service:
        name: docker
        state: started

    - name: Install docker-compose
      command: sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  
    - name: Make X
      command: sudo chmod +x /usr/local/bin/docker-compose

- name: Deploy nodejs app
  hosts: server
  become: yes
  tasks:
    - name: Copy nodejs folder to a server
      copy:
        src: ~/ansible-projects/simple-nodejs-app/nodejs-app-1.0.0.tgz
        dest: /home/ubuntu/nodejs-app.tgz
    - name: Unpack the nodejs file
      unarchive:
        src: /home/ubuntu/nodejs-app.tgz
        dest: /home/ubuntu/
        remote_src: yes
    - name: Install app dependencies
      npm:
        path: /home/ubuntu/package
    - name: Start the application
      command:
        chdir: /home/ubuntu/package/app
        cmd: node server.js
      async: 45
      poll: 0
        
