---
- name: Install docker and docker-compose
  hosts: server
  become: yes
  tasks:
    - name: Update yum repo and cache
      yum: update_cache=yes

    - name: Install docker
      yum:
        name: docker
        state: present

    - name: start docker
      service:
        name: docker
        state: started

    - name: Install docker-compose
      shell: sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  
    - name: Make file  executable
      command: sudo chmod +x /usr/local/bin/docker-compose

- name: Copy and run docker-compose file
  hosts: server
  become: yes
  tasks:
    - name: Copy docker-compose file to the server
      copy:
        src: ./docker-compose.yaml
        dest: /home/ec2-user/


    - name: Run docker compose file
      command: docker-compose up -d
      args:
        chdir: /home/ec2-user/
      